name: deployer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i
      - name: Build Docs
        run: pnpm docgen
      - name: Deploy to S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: docs
          bucket: ${{ secrets.S3_BUCKET }}/projects/hybrids-helpers
          delete-removed: projects/hybrids-helpers/**
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          no-cache: true
          private: true
